// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/dentist": {
            "post": {
                "description": "Add a dentist",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dentists"
                ],
                "summary": "Add a dentist",
                "parameters": [
                    {
                        "description": "Dentist",
                        "name": "dentist",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dentist.Dentist"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "TOKEN",
                        "in": "header"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dentist.Dentist"
                        }
                    }
                }
            }
        },
        "/dentist/{id}": {
            "get": {
                "description": "Get dentist by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dentists"
                ],
                "summary": "Get dentist by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dentist.Dentist"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a dentist",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dentists"
                ],
                "summary": "Update a dentist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dentist",
                        "name": "turno",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dentist.Dentist"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "TOKEN",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dentist.Dentist"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a dentist",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dentists"
                ],
                "summary": "Delete a dentist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "TOKEN",
                        "in": "header"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "dentist deleted",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/patient": {
            "post": {
                "description": "create patient",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patient"
                ],
                "summary": "Create Patient",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Patient",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/patient.Patient"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/patient.Patient"
                        }
                    }
                }
            }
        },
        "/patient/{id}": {
            "get": {
                "description": "get patient by Id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patient"
                ],
                "summary": "Get Patient By Id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/patient.Patient"
                        }
                    }
                }
            },
            "put": {
                "description": "update patient",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patient"
                ],
                "summary": "Update Patient",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "TOKEN",
                        "in": "header"
                    },
                    {
                        "description": "Patient",
                        "name": "patient",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/patient.Patient"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/patient.Patient"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete patient",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patient"
                ],
                "summary": "Delete Patient",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "TOKEN",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "patch": {
                "description": "patch patient",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patient"
                ],
                "summary": "Patch Patient",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "TOKEN",
                        "in": "header"
                    },
                    {
                        "description": "Patient",
                        "name": "patient",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/patient.Patient"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/patient.Patient"
                        }
                    }
                }
            }
        },
        "/turno": {
            "get": {
                "description": "Get turnos by Paciente ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "turnos"
                ],
                "summary": "Get turnos by Paciente ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "DNI",
                        "name": "dni",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/turno.Turno"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Add a turno",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "turnos"
                ],
                "summary": "Add a turno",
                "parameters": [
                    {
                        "description": "Turno",
                        "name": "turno",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/turno.Turno"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "TOKEN",
                        "in": "header"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/turno.Turno"
                        }
                    }
                }
            }
        },
        "/turno/{id}": {
            "get": {
                "description": "Get turno by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "turnos"
                ],
                "summary": "Get turno by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/turno.Turno"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a turno",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "turnos"
                ],
                "summary": "Update a turno",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Turno",
                        "name": "turno",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/turno.Turno"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "TOKEN",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/turno.Turno"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a turno",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "turnos"
                ],
                "summary": "Delete a turno",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "TOKEN",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "turno deleted",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update a turno with a patch",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "turnos"
                ],
                "summary": "Update a turno with a patch",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "TOKEN",
                        "in": "header"
                    },
                    {
                        "description": "Turno",
                        "name": "turno",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/turno.Turno"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/turno.Turno"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dentist.Dentist": {
            "type": "object",
            "required": [
                "apellido",
                "matricula",
                "nombre"
            ],
            "properties": {
                "apellido": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "matricula": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string"
                }
            }
        },
        "patient.Patient": {
            "type": "object",
            "required": [
                "apellido",
                "dni",
                "domicilio",
                "fecha_alta",
                "nombre"
            ],
            "properties": {
                "apellido": {
                    "type": "string"
                },
                "dni": {
                    "type": "string"
                },
                "domicilio": {
                    "type": "string"
                },
                "fecha_alta": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nombre": {
                    "type": "string"
                }
            }
        },
        "turno.Turno": {
            "type": "object",
            "properties": {
                "dentistaId": {
                    "type": "string"
                },
                "descripcion": {
                    "type": "string"
                },
                "fechaHora": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "pacienteDni": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Certified Tech Developer - Dentistas",
	Description:      "This API Handle Products.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
